#include 'totvs.ch'
#include 'topconn.ch'

//-----------------------------------------------------------------
/*/{Protheus.doc} ALPCP01
Inclui requisições de DGF (despesas gerais de fabricação)

@type       Function
@author     Julio Lisboa
@since      22/04/2025
/*/
//-----------------------------------------------------------------
User Function ALPCP01(lInPE)
	local lOk			:= .F.
	private lSD3Ajust	:= .F.
	default lInPE		:= .F.

	if lInPE .OR. FWISINCALLSTACK("U_SD3250I")
		BEGIN TRANSACTION
			If buscaDadosOP( SD3->D3_FILIAL , SD3->D3_OP, SD3->D3_DOC ,  @lOk )
				If lOk
					gravaStatus( SD3->D3_FILIAL , SD3->D3_OP, SD3->D3_DOC )
				endif
			else
				DisarmTransaction()
			endif
		END TRANSACTION
	else
		fPerg()
	endif

return

//-----------------------------------------------------------------
static function fPerg()
	local aParamBox		:= {}
	local aOpcSimNao	:= {"1=Sim","2=Nao"}

	aAdd(aParamBox,{1,"Data da OP de"			,Ctod("")	,""	,""	,""	,""	,60,.T.}) //MV_PAR01
	aAdd(aParamBox,{1,"Data da OP Ate"			,Ctod("")	,""	,""	,""	,""	,60,.T.}) //MV_PAR02
	aAdd(aParambox,{1,"OP de"					,Space(TamSx3("D3_OP")[1]),"","","SC2Q","",70,.F.})// MV_PAR03
	aAdd(aParambox,{1,"OP ate"					,Space(TamSx3("D3_OP")[1]),"","","SC2Q","",70,.T.})// MV_PAR04
	aAdd(aParamBox,{2,"Ajusta SD3",     		"2",aOpcSimNao, 60, '.T.', .T.}) //MV_PAR05

	If ParamBox(aParamBox,"Parametros",,,,.T.,,,,"ALPCP01",.T.,.T.)
		lSD3Ajust		:= alltrim( MV_PAR05 ) == "1"
		Processa( { || buscaOP() } )
	endif

return

//-----------------------------------------------------------------
static function retQueryOP(lDistinct,cFilOP,cNumOP,cDocOP,dDataIni,dDataFim,cOPDe,cOPAte)
	local cQuery		:= ""

	default lDistinct	:= .F.
	default cFilOP		:= ""
	default cNumOP		:= ""
	default cDocOP		:= ""
	default dDataIni	:= stod("")
	default dDataFim	:= stod("")
	default cOPDe		:= ""
	default cOPAte		:= ""

	cQuery	+= "SELECT" + CRLF
	if lDistinct
		cQuery	+= "	DISTINCT D3_FILIAL,D3_OP,D3_DOC" + CRLF
	else
		cQuery	+= "	D3_FILIAL,D3_TM,D3_COD,D3_UM,D3_CF,D3_QUANT,D3_OP,D3_DOC,SD3.R_E_C_N_O_ REC_SD3" + CRLF
	endif
	cQuery	+= "FROM" + CRLF
	cQuery	+= "	" + retsqlname("SD3") + " SD3" + CRLF
	cQuery	+= "	INNER JOIN " + CRLF
	cQuery	+= "		" + retsqlname("SC2") + " SC2 " + CRLF
	cQuery	+= "			ON SC2.D_E_L_E_T_ = ' ' " + CRLF
	cQuery	+= "			AND C2_FILIAL = D3_FILIAL " + CRLF
	cQuery	+= "			AND C2_NUM + C2_ITEM + C2_SEQUEN = D3_OP" + CRLF
	//cQuery	+= "			AND C2_DATRF = '' " + CRLF
	cQuery	+= "WHERE" + CRLF
	cQuery	+= "	SD3.D_E_L_E_T_ = ' '" + CRLF

	if lDistinct
		cQuery	+= "	AND D3_FILIAL = '" + FwXFilial("SD3") + "' " + CRLF
		cQuery	+= "	AND D3_EMISSAO BETWEEN '" + DTOS(dDataIni) + "' AND '" + DTOS(dDataFim) + "'" + CRLF
		cQuery	+= "	AND D3_OP BETWEEN '" + cOPDe + "' AND '" + cOPAte + "'" + CRLF
	else
		cQuery	+= "	AND D3_FILIAL = '" + cFilOP + "' " + CRLF
		cQuery	+= "	AND D3_OP = '" + cNumOP + "' " + CRLF

		if !Empty(cDocOP)
			cQuery	+= "	AND D3_DOC = '" + cDocOP + "' " + CRLF
		endif
	endif

	cQuery	+= "	AND D3_ESTORNO <> 'S' " + CRLF
	cQuery	+= "	AND ( D3_CF IN ('PR0','PR1') OR D3_CC <> '' ) " + CRLF
	cQuery	+= "	AND D3_ZZINT <> 'S' " + CRLF
	cQuery	+= "	AND D3_TM NOT IN ('503') " + CRLF

	if !lDistinct
		cQuery	+= "ORDER BY" + CRLF
		cQuery	+= "	SD3.D3_FILIAL,SD3.D3_OP,SD3.D3_TM,SD3.D3_DOC,SD3.D3_NUMSEQ " + CRLF
	endif

return cQuery

//-----------------------------------------------------------------
static function buscaOP()

	local cQuery	:= retQueryOP(.T.,"","","",MV_PAR01,MV_PAR02,MV_PAR03,MV_PAR04)
	local cAlias	:= getnextAlias()
	local nTotalOP	:= 0
	local lOk		:= .F.

	If lSD3Ajust
		BEGIN TRANSACTION
			ajustaSD3()
			gravaCC()
		END TRANSACTION
	endif

	TcQuery cQuery new alias &cAlias
	Count to nTotalOP
	(cAlias)->(DbGoTop())

	if (cAlias)->(!Eof())
		while (cAlias)->(!Eof())
			IncProc()
			BEGIN TRANSACTION
				If buscaDadosOP( (cAlias)->D3_FILIAL , (cAlias)->D3_OP, (cAlias)->D3_DOC , @lOk )
					If lOk
						gravaStatus( (cAlias)->D3_FILIAL , (cAlias)->D3_OP )
					endif
				else
					DisarmTransaction()
				endif
			END TRANSACTION

			(cAlias)->(DbSkip())
		endDo
	else
		FwAlertError("Nenhum dado localizado com os parâmetros informados para geração do DGF!",Fundesc())
	EndIf
	(cAlias)->(DbCloseArea())

return

//-----------------------------------------------------------------
static function buscaDadosOP(cFilOP,cOP,cDoc,lOk)
	local cQuery		:= retQueryOP(.F.,cFilOP,cOP,cDoc)
	local cAlias		:= getnextAlias()
	local aAreaSD3		:= SD3->(GetArea())
	local aAreaSC2		:= SC2->(GetArea())
	local lRet			:= .T.
	local cID			:= ""
	local dDataOP		:= stod("")

	TcQuery cQuery new alias &cAlias
	if (cAlias)->(!Eof())
		SD3->(DbSetOrder(1)) //D3_FILIAL+D3_OP+D3_COD+D3_LOCAL
		SC2->(DbSetOrder(1)) //C2_FILIAL+C2_NUM+C2_ITEM+C2_SEQUEN+C2_ITEMGRD

		while (cAlias)->(!Eof())
			SD3->(DbGoTo( (cAlias)->REC_SD3 ))
			If SC2->(DbSeek( SD3->(D3_FILIAL+D3_OP) ))

				dDataOP	:= SC2->C2_DATRF
				If !empty(SC2->C2_DATRF)
					grvDtOP(STOD(""))
				endif

				If alltrim( SD3->D3_CF ) $ "PR0/PR1"
					nQtdProd		:= SD3->D3_QUANT
				else
					cID			:= FWUUIDV4()
					lRet		:= fProcess( SD3->D3_CC, SD3->D3_COD , nQtdProd, SD3->D3_QUANT , SD3->D3_OP, cID )
					if lRet
						If reclock("SD3",.F.)
							SD3->D3_ZZID		:= cID
							SD3->(MsUnlock())
						endif
						lOk		:= .T.
					else
						grvDtOP(dDataOP)
						lOk		:= .F.
						exit
					endif
				endif
				grvDtOP(dDataOP)
			endif
			(cAlias)->(DbSkip())
		endDo
	else
		lOk		:= .F.
		lRet	:= .T.
	endif
	(cAlias)->(DbCloseArea())
	restArea(aAreaSC2)
	restArea(aAreaSD3)

return lRet

//-----------------------------------------------------------------
static function fProcess(cCC,cProduto,nQtde,nQtdMOD,cOP,cID)

	local aItAux                := {}
	local aItens                := {}
	local aCab                  := {}
	local lRet                  := .F.
	local cQuery                := retQueryProdutos(cCC,cProduto)
	local cAlias                := getnextAlias()
	local aAreaSD3				:= SD3->(GetArea())
	local dDataBkp				:= dDataBase

	private lMsErroAuto			:= .F.
	private lMsHelpAuto	    	:= .T.
	private lAutoErrNoFile		:= .T.

	dDataBase		:= SD3->D3_EMISSAO
	aAdd( aCab, {"D3_TM",       "503",                              nil })
	aAdd( aCab, {"D3_CC",       cCC,                                nil })
	aAdd( aCab, {"D3_EMISSAO",  dDataBase,                          nil })
	//aAdd( aCab, {"D3_DOC",      NextNumero("SD3",2,"D3_DOC",.T.),   nil })

	TcQuery cQuery new alias &cAlias
	While (cAlias)->(!Eof())
		aItAux      := {}

		If alltrim( (cAlias)->B1_UM ) == "UN"
			aAdd( aItAux, {"D3_QUANT"	,nQtde,        nil })
		elseif alltrim( (cAlias)->B1_UM ) == "HR"
			aAdd( aItAux, {"D3_QUANT"	,nQtdMOD,        nil })
		endif

		aAdd( aItAux, {"D3_COD"		,(cAlias)->B1_COD,          		nil })
		aAdd( aItAux, {"D3_UM"		,(cAlias)->B1_UM,           		nil })
		aAdd( aItAux, {"D3_LOCAL"	,(cAlias)->B1_LOCPAD,        		nil })
		aAdd( aItAux, {"D3_OP"		,cOP,                       		nil })
		aAdd( aItAux, {"D3_ZZID"	,cID,                       		nil })
		aAdd( aItAux, {"D3_ZZINT"	,"I",                       		nil })
		aAdd( aItAux, {"D3_ZZDTINT"	,DTOC(Date()) + " - " + Time(),		nil })

		aadd(aItens,aItAux)
		(cAlias)->(dbSkip())
	EndDo

	if len(aItens) > 0
		MSExecAuto({|x,y| MATA241(x,y)},aCab,aItens,3)
		If lMsErroAuto
			cErro		:= retornaErro()
			FwAlertError("ERRO" + CRLF + CRLF + cErro,FunDesc())
		else
			lRet		:= .T.
		EndIf
	endif

	dDataBase		:= dDataBkp
	restArea(aAreaSD3)

return lRet

//-----------------------------------------------------------------
static function retQueryProdutos(cCC,cProduto)
	local cQuery        := ""

	cQuery      += "SELECT " + CRLF
	cQuery      += "    B1_COD,B1_DESC,B1_UM,B1_LOCPAD" + CRLF
	cQuery      += "FROM " + CRLF
	cQuery      += "    " + retsqlname("SB1") + CRLF
	cQuery      += "WHERE " + CRLF
	cQuery      += "    D_E_L_E_T_ = ' ' " + CRLF
	cQuery      += "    AND B1_CCCUSTO = '" + cCC +"' " + CRLF
	cQuery      += "    AND B1_GCCUSTO <> '' " + CRLF
	cQuery		+= "	AND B1_COD NOT IN ('" + cProduto + "') " + CRLF
	cQuery 		+= " 	AND B1_MSBLQL <> '1' " + CRLF
	cQuery      += "" + CRLF

return cQuery

//-----------------------------------------------------------------
static function retornaErro()
	local aLog			:= {}
	local nErro			:= 0
	local cErro			:= ""
	aLog        := GetAutoGRLog()
	For nErro := 1 To Len(aLog)
		If !Empty(cErro)
			cErro += CRLF
		EndIf
		cErro += aLog[nErro]
	Next nErro
return cErro

//-----------------------------------------------------------------
static function gravaStatus(cFilOP,cOP,cDoc)
	local cQuery	:= ""
	local cAlias	:= getnextAlias()
	local aAreaSD3	:= SD3->(GetArea())

	default cFilOP	:= FwXFilial("SD3")
	default cOP		:= ""
	default cDoc	:= ""

	cQuery	+= "SELECT" + CRLF
	cQuery	+= "	SD3.R_E_C_N_O_ AS REC_SD3 " + CRLF
	cQuery	+= "FROM" + CRLF
	cQuery	+= "	" + retsqlname("SD3") + " SD3" + CRLF
	cQuery	+= "WHERE" + CRLF
	cQuery	+= "	SD3.D_E_L_E_T_ = ' '" + CRLF
	cQuery	+= "	AND D3_FILIAL = '" + cFilOP + "'" + CRLF
	cQuery	+= "	AND D3_OP = '" + cOP + "'" + CRLF

	if !Empty(cDoc)
		cQuery	+= "	AND D3_DOC = '" + cDoc + "'" + CRLF
	endif

	cQuery	+= "	AND D3_ESTORNO = ''" + CRLF

	TcQuery cQuery new alias &cAlias
	if (cAlias)->(!Eof())
		SD3->(DbSetOrder(1)) //D3_FILIAL+D3_OP+D3_COD+D3_LOCAL
		while (cAlias)->(!Eof())
			SD3->(DbGoTo( (cAlias)->REC_SD3 ))
			if Reclock("SD3",.F.)
				SD3->D3_ZZINT		:= "S"
				SD3->D3_ZZDTINT		:= DTOC(Date()) + " - " + Time()
				SD3->(MsUnlock())
			endif
			(cAlias)->(DbSkip())
		endDo
	endif
	(cAlias)->(DbCloseArea())
	restArea(aAreaSD3)

return

//-----------------------------------------------------------------
static function grvDtOP(dDataOP)
	If Reclock("SC2",.F.)
		SC2->C2_DATRF		:= dDataOP
		SC2->(MsUnlock())
	endif
return

//-----------------------------------------------------------------
static function ajustaSD3()
	//Rotina solicitada pelo analista RICARDO SCATAMBURLO em 07/05/2025
	//E enviada por e-mail com cópia para o wagner.nardini@aluxdobrasil.com.br
	local cQuery		:= ""
	local cAlias		:= getnextAlias()
	local cFilOP		:= ""
	local cOP			:= ""
	local lOkAjust		:= .F.

	cQuery	+= "SELECT " + CRLF
	cQuery	+= "	DISTINCT D3_FILIAL,D3_OP" + CRLF
	cQuery	+= "FROM " + CRLF
	cQuery	+= "	" + retsqlname("SD3") + CRLF
	cQuery	+= "WHERE" + CRLF
	cQuery	+= "	D_E_L_E_T_ = ' ' " + CRLF
	cQuery	+= "	AND D3_TIPO = 'MO' " + CRLF
	cQuery	+= "	AND SUBSTRING(D3_COD,1,3) = 'MOD' " + CRLF
	cQuery	+= "	AND D3_EMISSAO BETWEEN '" + DTOS(MV_PAR01) + "' AND '" + DTOS(MV_PAR02) + "'" + CRLF
	cQuery	+= "	AND D3_OP BETWEEN '" + MV_PAR03 + "' AND '" + MV_PAR04 + "'" + CRLF
	cQuery	+= "" + CRLF

	TcQuery cQuery new alias &cAlias
	If (cAlias)->(!Eof())
		SD3->(DbSetOrder(1)) //D3_FILIAL+D3_OP+D3_COD+D3_LOCAL
		While (cAlias)->(!Eof())
			cFilOP		:= (cAlias)->D3_FILIAL
			cOP			:= (cAlias)->D3_OP

			If SD3->(DbSeek( cFilOP + cOP ))
				While SD3->(!Eof()) .and. SD3->(D3_FILIAL+D3_OP) == (cFilOP+cOP)
					If alltrim( SD3->D3_TIPO ) == "MO" .and. SubStr( SD3->D3_COD , 1 , 3 ) == "MOD"
						If Reclock("SD3",.F.)
							SD3->D3_COD		:= StrTran( SD3->D3_COD, "MOD", "MO" )
							SD3->(MsUnlock())
							lOkAjust		:= .T.
						endif
					endif
					SD3->(DbSkip())
				endDo
			endif
			(cAlias)->(DbSkip())
		endDo
	endif
	(cAlias)->(DbCloseArea())

	If lOkAjust
		FWAlertSuccess("Registros da SD3 ajustados com sucesso!",Fundesc())
	else
		FwAlertError("Nenhuma OP (SD3) foi localizada/ajustada",Fundesc())
	endif
return

//-----------------------------------------------------------------
static function gravaCC()
	local cQuery        := ""
	local cAlias        := getnextAlias()
	local aAreaSD3      := SD3->(GetArea())

	cQuery  += "SELECT" + CRLF
	cQuery  += "    SD3.R_E_C_N_O_ AS D3_RECNO" + CRLF
	cQuery  += "    ,B1_CCCUSTO" + CRLF
	cQuery  += "FROM" + CRLF
	cQuery  += "    " + retsqlname("SD3") + " SD3" + CRLF
	cQuery  += "INNER JOIN " + retsqlname("SB1") + " SB1 ON SB1.D_E_L_E_T_ = ' '" + CRLF
	cQuery  += "    AND B1_COD = D3_COD" + CRLF
	cQuery  += "WHERE" + CRLF
	cQuery  += "    SD3.D_E_L_E_T_ = ' '" + CRLF
	cQuery	+= "	AND D3_EMISSAO BETWEEN '" + DTOS(MV_PAR01) + "' AND '" + DTOS(MV_PAR02) + "'" + CRLF
	cQuery	+= "	AND D3_OP BETWEEN '" + MV_PAR03 + "' AND '" + MV_PAR04 + "'" + CRLF
	cQuery  += "    AND D3_CC = ''" + CRLF
	cQuery  += "    AND B1_CCCUSTO <> ''" + CRLF
	cQuery  += "    AND B1_GCCUSTO <> '' " + CRLF
	cQuery	+= " 	AND B1_MSBLQL <> '1' " + CRLF

	TcQuery cQuery new alias &cAlias
	while (cAlias)->(!eof())
		SD3->(DbGoTo( (cAlias)->D3_RECNO ))
		If Reclock("SD3",.F.)
			SD3->D3_CC  := (cAlias)->B1_CCCUSTO
			SD3->(MsUnlock())
		endif
		(cAlias)->(Dbskip())
	endDo
	(cAlias)->(DbCloseArea())
	restArea(aAreaSD3)
return
